// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gcp.container.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ClusterDatabaseEncryption {
    /**
     * @return the key to use to encrypt/decrypt secrets.  See the [DatabaseEncryption definition](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.DatabaseEncryption) for more information.
     * 
     * &lt;a name=&#34;nestedEnableK8sBetaApis&#34;&gt;&lt;/a&gt;The `enableK8sBetaApis` block supports:
     * 
     */
    private @Nullable String keyName;
    /**
     * @return `ENCRYPTED` or `DECRYPTED`
     * 
     */
    private String state;

    private ClusterDatabaseEncryption() {}
    /**
     * @return the key to use to encrypt/decrypt secrets.  See the [DatabaseEncryption definition](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.DatabaseEncryption) for more information.
     * 
     * &lt;a name=&#34;nestedEnableK8sBetaApis&#34;&gt;&lt;/a&gt;The `enableK8sBetaApis` block supports:
     * 
     */
    public Optional<String> keyName() {
        return Optional.ofNullable(this.keyName);
    }
    /**
     * @return `ENCRYPTED` or `DECRYPTED`
     * 
     */
    public String state() {
        return this.state;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ClusterDatabaseEncryption defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String keyName;
        private String state;
        public Builder() {}
        public Builder(ClusterDatabaseEncryption defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.keyName = defaults.keyName;
    	      this.state = defaults.state;
        }

        @CustomType.Setter
        public Builder keyName(@Nullable String keyName) {

            this.keyName = keyName;
            return this;
        }
        @CustomType.Setter
        public Builder state(String state) {
            if (state == null) {
              throw new MissingRequiredPropertyException("ClusterDatabaseEncryption", "state");
            }
            this.state = state;
            return this;
        }
        public ClusterDatabaseEncryption build() {
            final var _resultValue = new ClusterDatabaseEncryption();
            _resultValue.keyName = keyName;
            _resultValue.state = state;
            return _resultValue;
        }
    }
}
