// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gcp.networksecurity;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class FirewallEndpointAssociationArgs extends com.pulumi.resources.ResourceArgs {

    public static final FirewallEndpointAssociationArgs Empty = new FirewallEndpointAssociationArgs();

    /**
     * Whether the association is disabled. True indicates that traffic will not be intercepted.
     * &gt; **Note:** The API will reject the request if this value is set to true when creating the resource,
     * otherwise on an update the association can be disabled.
     * 
     */
    @Import(name="disabled")
    private @Nullable Output<Boolean> disabled;

    /**
     * @return Whether the association is disabled. True indicates that traffic will not be intercepted.
     * &gt; **Note:** The API will reject the request if this value is set to true when creating the resource,
     * otherwise on an update the association can be disabled.
     * 
     */
    public Optional<Output<Boolean>> disabled() {
        return Optional.ofNullable(this.disabled);
    }

    /**
     * The URL of the firewall endpoint that is being associated.
     * 
     */
    @Import(name="firewallEndpoint", required=true)
    private Output<String> firewallEndpoint;

    /**
     * @return The URL of the firewall endpoint that is being associated.
     * 
     */
    public Output<String> firewallEndpoint() {
        return this.firewallEndpoint;
    }

    /**
     * A map of key/value label pairs to assign to the resource.
     * 
     * **Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
     * Please refer to the field `effective_labels` for all of the labels present on the resource.
     * 
     */
    @Import(name="labels")
    private @Nullable Output<Map<String,String>> labels;

    /**
     * @return A map of key/value label pairs to assign to the resource.
     * 
     * **Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
     * Please refer to the field `effective_labels` for all of the labels present on the resource.
     * 
     */
    public Optional<Output<Map<String,String>>> labels() {
        return Optional.ofNullable(this.labels);
    }

    /**
     * The location (zone) of the firewall endpoint association.
     * 
     */
    @Import(name="location", required=true)
    private Output<String> location;

    /**
     * @return The location (zone) of the firewall endpoint association.
     * 
     */
    public Output<String> location() {
        return this.location;
    }

    /**
     * The name of the firewall endpoint association resource.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the firewall endpoint association resource.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The URL of the network that is being associated.
     * 
     */
    @Import(name="network", required=true)
    private Output<String> network;

    /**
     * @return The URL of the network that is being associated.
     * 
     */
    public Output<String> network() {
        return this.network;
    }

    /**
     * The name of the parent this firewall endpoint association belongs to.
     * Format: projects/{project_id}.
     * 
     */
    @Import(name="parent")
    private @Nullable Output<String> parent;

    /**
     * @return The name of the parent this firewall endpoint association belongs to.
     * Format: projects/{project_id}.
     * 
     */
    public Optional<Output<String>> parent() {
        return Optional.ofNullable(this.parent);
    }

    /**
     * The URL of the TlsInspectionPolicy that is being associated.
     * 
     */
    @Import(name="tlsInspectionPolicy")
    private @Nullable Output<String> tlsInspectionPolicy;

    /**
     * @return The URL of the TlsInspectionPolicy that is being associated.
     * 
     */
    public Optional<Output<String>> tlsInspectionPolicy() {
        return Optional.ofNullable(this.tlsInspectionPolicy);
    }

    private FirewallEndpointAssociationArgs() {}

    private FirewallEndpointAssociationArgs(FirewallEndpointAssociationArgs $) {
        this.disabled = $.disabled;
        this.firewallEndpoint = $.firewallEndpoint;
        this.labels = $.labels;
        this.location = $.location;
        this.name = $.name;
        this.network = $.network;
        this.parent = $.parent;
        this.tlsInspectionPolicy = $.tlsInspectionPolicy;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(FirewallEndpointAssociationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private FirewallEndpointAssociationArgs $;

        public Builder() {
            $ = new FirewallEndpointAssociationArgs();
        }

        public Builder(FirewallEndpointAssociationArgs defaults) {
            $ = new FirewallEndpointAssociationArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param disabled Whether the association is disabled. True indicates that traffic will not be intercepted.
         * &gt; **Note:** The API will reject the request if this value is set to true when creating the resource,
         * otherwise on an update the association can be disabled.
         * 
         * @return builder
         * 
         */
        public Builder disabled(@Nullable Output<Boolean> disabled) {
            $.disabled = disabled;
            return this;
        }

        /**
         * @param disabled Whether the association is disabled. True indicates that traffic will not be intercepted.
         * &gt; **Note:** The API will reject the request if this value is set to true when creating the resource,
         * otherwise on an update the association can be disabled.
         * 
         * @return builder
         * 
         */
        public Builder disabled(Boolean disabled) {
            return disabled(Output.of(disabled));
        }

        /**
         * @param firewallEndpoint The URL of the firewall endpoint that is being associated.
         * 
         * @return builder
         * 
         */
        public Builder firewallEndpoint(Output<String> firewallEndpoint) {
            $.firewallEndpoint = firewallEndpoint;
            return this;
        }

        /**
         * @param firewallEndpoint The URL of the firewall endpoint that is being associated.
         * 
         * @return builder
         * 
         */
        public Builder firewallEndpoint(String firewallEndpoint) {
            return firewallEndpoint(Output.of(firewallEndpoint));
        }

        /**
         * @param labels A map of key/value label pairs to assign to the resource.
         * 
         * **Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
         * Please refer to the field `effective_labels` for all of the labels present on the resource.
         * 
         * @return builder
         * 
         */
        public Builder labels(@Nullable Output<Map<String,String>> labels) {
            $.labels = labels;
            return this;
        }

        /**
         * @param labels A map of key/value label pairs to assign to the resource.
         * 
         * **Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
         * Please refer to the field `effective_labels` for all of the labels present on the resource.
         * 
         * @return builder
         * 
         */
        public Builder labels(Map<String,String> labels) {
            return labels(Output.of(labels));
        }

        /**
         * @param location The location (zone) of the firewall endpoint association.
         * 
         * @return builder
         * 
         */
        public Builder location(Output<String> location) {
            $.location = location;
            return this;
        }

        /**
         * @param location The location (zone) of the firewall endpoint association.
         * 
         * @return builder
         * 
         */
        public Builder location(String location) {
            return location(Output.of(location));
        }

        /**
         * @param name The name of the firewall endpoint association resource.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the firewall endpoint association resource.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param network The URL of the network that is being associated.
         * 
         * @return builder
         * 
         */
        public Builder network(Output<String> network) {
            $.network = network;
            return this;
        }

        /**
         * @param network The URL of the network that is being associated.
         * 
         * @return builder
         * 
         */
        public Builder network(String network) {
            return network(Output.of(network));
        }

        /**
         * @param parent The name of the parent this firewall endpoint association belongs to.
         * Format: projects/{project_id}.
         * 
         * @return builder
         * 
         */
        public Builder parent(@Nullable Output<String> parent) {
            $.parent = parent;
            return this;
        }

        /**
         * @param parent The name of the parent this firewall endpoint association belongs to.
         * Format: projects/{project_id}.
         * 
         * @return builder
         * 
         */
        public Builder parent(String parent) {
            return parent(Output.of(parent));
        }

        /**
         * @param tlsInspectionPolicy The URL of the TlsInspectionPolicy that is being associated.
         * 
         * @return builder
         * 
         */
        public Builder tlsInspectionPolicy(@Nullable Output<String> tlsInspectionPolicy) {
            $.tlsInspectionPolicy = tlsInspectionPolicy;
            return this;
        }

        /**
         * @param tlsInspectionPolicy The URL of the TlsInspectionPolicy that is being associated.
         * 
         * @return builder
         * 
         */
        public Builder tlsInspectionPolicy(String tlsInspectionPolicy) {
            return tlsInspectionPolicy(Output.of(tlsInspectionPolicy));
        }

        public FirewallEndpointAssociationArgs build() {
            if ($.firewallEndpoint == null) {
                throw new MissingRequiredPropertyException("FirewallEndpointAssociationArgs", "firewallEndpoint");
            }
            if ($.location == null) {
                throw new MissingRequiredPropertyException("FirewallEndpointAssociationArgs", "location");
            }
            if ($.network == null) {
                throw new MissingRequiredPropertyException("FirewallEndpointAssociationArgs", "network");
            }
            return $;
        }
    }

}
