// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gcp.vmwareengine.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.util.Objects;


public final class PrivateCloudManagementClusterAutoscalingSettingsAutoscalingPolicyConsumedMemoryThresholdsArgs extends com.pulumi.resources.ResourceArgs {

    public static final PrivateCloudManagementClusterAutoscalingSettingsAutoscalingPolicyConsumedMemoryThresholdsArgs Empty = new PrivateCloudManagementClusterAutoscalingSettingsAutoscalingPolicyConsumedMemoryThresholdsArgs();

    /**
     * The utilization triggering the scale-in operation in percent.
     * 
     */
    @Import(name="scaleIn", required=true)
    private Output<Integer> scaleIn;

    /**
     * @return The utilization triggering the scale-in operation in percent.
     * 
     */
    public Output<Integer> scaleIn() {
        return this.scaleIn;
    }

    /**
     * The utilization triggering the scale-out operation in percent.
     * 
     */
    @Import(name="scaleOut", required=true)
    private Output<Integer> scaleOut;

    /**
     * @return The utilization triggering the scale-out operation in percent.
     * 
     */
    public Output<Integer> scaleOut() {
        return this.scaleOut;
    }

    private PrivateCloudManagementClusterAutoscalingSettingsAutoscalingPolicyConsumedMemoryThresholdsArgs() {}

    private PrivateCloudManagementClusterAutoscalingSettingsAutoscalingPolicyConsumedMemoryThresholdsArgs(PrivateCloudManagementClusterAutoscalingSettingsAutoscalingPolicyConsumedMemoryThresholdsArgs $) {
        this.scaleIn = $.scaleIn;
        this.scaleOut = $.scaleOut;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PrivateCloudManagementClusterAutoscalingSettingsAutoscalingPolicyConsumedMemoryThresholdsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PrivateCloudManagementClusterAutoscalingSettingsAutoscalingPolicyConsumedMemoryThresholdsArgs $;

        public Builder() {
            $ = new PrivateCloudManagementClusterAutoscalingSettingsAutoscalingPolicyConsumedMemoryThresholdsArgs();
        }

        public Builder(PrivateCloudManagementClusterAutoscalingSettingsAutoscalingPolicyConsumedMemoryThresholdsArgs defaults) {
            $ = new PrivateCloudManagementClusterAutoscalingSettingsAutoscalingPolicyConsumedMemoryThresholdsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param scaleIn The utilization triggering the scale-in operation in percent.
         * 
         * @return builder
         * 
         */
        public Builder scaleIn(Output<Integer> scaleIn) {
            $.scaleIn = scaleIn;
            return this;
        }

        /**
         * @param scaleIn The utilization triggering the scale-in operation in percent.
         * 
         * @return builder
         * 
         */
        public Builder scaleIn(Integer scaleIn) {
            return scaleIn(Output.of(scaleIn));
        }

        /**
         * @param scaleOut The utilization triggering the scale-out operation in percent.
         * 
         * @return builder
         * 
         */
        public Builder scaleOut(Output<Integer> scaleOut) {
            $.scaleOut = scaleOut;
            return this;
        }

        /**
         * @param scaleOut The utilization triggering the scale-out operation in percent.
         * 
         * @return builder
         * 
         */
        public Builder scaleOut(Integer scaleOut) {
            return scaleOut(Output.of(scaleOut));
        }

        public PrivateCloudManagementClusterAutoscalingSettingsAutoscalingPolicyConsumedMemoryThresholdsArgs build() {
            if ($.scaleIn == null) {
                throw new MissingRequiredPropertyException("PrivateCloudManagementClusterAutoscalingSettingsAutoscalingPolicyConsumedMemoryThresholdsArgs", "scaleIn");
            }
            if ($.scaleOut == null) {
                throw new MissingRequiredPropertyException("PrivateCloudManagementClusterAutoscalingSettingsAutoscalingPolicyConsumedMemoryThresholdsArgs", "scaleOut");
            }
            return $;
        }
    }

}
