provider: gcp
gcp: true
major-version: 8
parallel: 2
providerVersion: "github.com/hashicorp/terraform-provider-google-beta/version.ProviderVersion"
esc:
  enabled: true
env:
  GOOGLE_CI_SERVICE_ACCOUNT_EMAIL: pulumi-ci@pulumi-ci-gcp-provider.iam.gserviceaccount.com
  GOOGLE_CI_WORKLOAD_IDENTITY_POOL: pulumi-ci
  GOOGLE_CI_WORKLOAD_IDENTITY_PROVIDER: pulumi-ci
  GOOGLE_PROJECT: "pulumi-ci-gcp-provider"
  GOOGLE_PROJECT_NUMBER: 895284651812
  GOOGLE_REGION: "us-central1"
  GOOGLE_ZONE: "us-central1-a"
  PULUMI_MISSING_DOCS_ERROR: true
upstream-provider-repo: terraform-provider-google-beta
makeTemplate: bridged
plugins:
  - name: random
    version: "4.16.1"
  - name: kubernetes
    version: "4.11.0"
  - name: std
    version: "1.6.2"
  - name: tls
    version: "5.0.2"
  - name: http
    version: "0.0.3"
  - name: time
    version: "0.0.15"
  - name: terraform
    version: "1.0.17"
    kind: converter
goBuildParallelism: 2
# Use `pulumi convert` for translating examples from TF to Pulumi.
pulumiConvert: 1
integrationTestProvider: true
allowMissingDocs: false
releaseVerification:
  nodejs: examples/bucket
  python: examples/bucket-py
  dotnet: examples/serverless-cs
  go: examples/bucket-go
autoMergeProviderUpgrades: false
