archives:
- id: archive
  name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
  - make tfgen
blobs:
- bucket: get.pulumi.com
  folder: releases/plugins/
  ids:
  - archive
  provider: s3
  region: us-west-2
builds:
- binary: pulumi-resource-gcp
  dir: provider
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - windows
  - linux
  ldflags:
  - -X github.com/pulumi/pulumi-gcp/provider/v6/pkg/version.Version={{.Tag}}
  - -X github.com/hashicorp/terraform-provider-google-beta/version.ProviderVersion={{.Tag}}
  main: ./cmd/pulumi-resource-gcp/
changelog:
  use: git
  sort: asc
release:
  disable: false
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
