// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gcp.dataflow.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.gcp.dataflow.outputs.PipelineWorkloadDataflowFlexTemplateRequest;
import com.pulumi.gcp.dataflow.outputs.PipelineWorkloadDataflowLaunchTemplateRequest;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class PipelineWorkload {
    /**
     * @return Template information and additional parameters needed to launch a Dataflow job using the flex launch API.
     * https://cloud.google.com/dataflow/docs/reference/data-pipelines/rest/v1/projects.locations.pipelines#launchflextemplaterequest
     * Structure is documented below.
     * 
     */
    private @Nullable PipelineWorkloadDataflowFlexTemplateRequest dataflowFlexTemplateRequest;
    /**
     * @return Template information and additional parameters needed to launch a Dataflow job using the standard launch API.
     * https://cloud.google.com/dataflow/docs/reference/data-pipelines/rest/v1/projects.locations.pipelines#launchtemplaterequest
     * Structure is documented below.
     * 
     */
    private @Nullable PipelineWorkloadDataflowLaunchTemplateRequest dataflowLaunchTemplateRequest;

    private PipelineWorkload() {}
    /**
     * @return Template information and additional parameters needed to launch a Dataflow job using the flex launch API.
     * https://cloud.google.com/dataflow/docs/reference/data-pipelines/rest/v1/projects.locations.pipelines#launchflextemplaterequest
     * Structure is documented below.
     * 
     */
    public Optional<PipelineWorkloadDataflowFlexTemplateRequest> dataflowFlexTemplateRequest() {
        return Optional.ofNullable(this.dataflowFlexTemplateRequest);
    }
    /**
     * @return Template information and additional parameters needed to launch a Dataflow job using the standard launch API.
     * https://cloud.google.com/dataflow/docs/reference/data-pipelines/rest/v1/projects.locations.pipelines#launchtemplaterequest
     * Structure is documented below.
     * 
     */
    public Optional<PipelineWorkloadDataflowLaunchTemplateRequest> dataflowLaunchTemplateRequest() {
        return Optional.ofNullable(this.dataflowLaunchTemplateRequest);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PipelineWorkload defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable PipelineWorkloadDataflowFlexTemplateRequest dataflowFlexTemplateRequest;
        private @Nullable PipelineWorkloadDataflowLaunchTemplateRequest dataflowLaunchTemplateRequest;
        public Builder() {}
        public Builder(PipelineWorkload defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.dataflowFlexTemplateRequest = defaults.dataflowFlexTemplateRequest;
    	      this.dataflowLaunchTemplateRequest = defaults.dataflowLaunchTemplateRequest;
        }

        @CustomType.Setter
        public Builder dataflowFlexTemplateRequest(@Nullable PipelineWorkloadDataflowFlexTemplateRequest dataflowFlexTemplateRequest) {

            this.dataflowFlexTemplateRequest = dataflowFlexTemplateRequest;
            return this;
        }
        @CustomType.Setter
        public Builder dataflowLaunchTemplateRequest(@Nullable PipelineWorkloadDataflowLaunchTemplateRequest dataflowLaunchTemplateRequest) {

            this.dataflowLaunchTemplateRequest = dataflowLaunchTemplateRequest;
            return this;
        }
        public PipelineWorkload build() {
            final var _resultValue = new PipelineWorkload();
            _resultValue.dataflowFlexTemplateRequest = dataflowFlexTemplateRequest;
            _resultValue.dataflowLaunchTemplateRequest = dataflowLaunchTemplateRequest;
            return _resultValue;
        }
    }
}
