// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gcp.gkehub.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetFeatureStateState {
    /**
     * @return The high-level, machine-readable status of this Feature.
     * 
     */
    private String code;
    /**
     * @return A human-readable description of the current status.
     * 
     */
    private String description;
    /**
     * @return The time this status and any related Feature-specific details were updated. A timestamp in RFC3339 UTC &#34;Zulu&#34; format, with nanosecond resolution and up to nine fractional digits. Examples: &#34;2014-10-02T15:01:23Z&#34; and &#34;2014-10-02T15:01:23.045123456Z&#34;
     * 
     */
    private String updateTime;

    private GetFeatureStateState() {}
    /**
     * @return The high-level, machine-readable status of this Feature.
     * 
     */
    public String code() {
        return this.code;
    }
    /**
     * @return A human-readable description of the current status.
     * 
     */
    public String description() {
        return this.description;
    }
    /**
     * @return The time this status and any related Feature-specific details were updated. A timestamp in RFC3339 UTC &#34;Zulu&#34; format, with nanosecond resolution and up to nine fractional digits. Examples: &#34;2014-10-02T15:01:23Z&#34; and &#34;2014-10-02T15:01:23.045123456Z&#34;
     * 
     */
    public String updateTime() {
        return this.updateTime;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetFeatureStateState defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String code;
        private String description;
        private String updateTime;
        public Builder() {}
        public Builder(GetFeatureStateState defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.code = defaults.code;
    	      this.description = defaults.description;
    	      this.updateTime = defaults.updateTime;
        }

        @CustomType.Setter
        public Builder code(String code) {
            if (code == null) {
              throw new MissingRequiredPropertyException("GetFeatureStateState", "code");
            }
            this.code = code;
            return this;
        }
        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetFeatureStateState", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder updateTime(String updateTime) {
            if (updateTime == null) {
              throw new MissingRequiredPropertyException("GetFeatureStateState", "updateTime");
            }
            this.updateTime = updateTime;
            return this;
        }
        public GetFeatureStateState build() {
            final var _resultValue = new GetFeatureStateState();
            _resultValue.code = code;
            _resultValue.description = description;
            _resultValue.updateTime = updateTime;
            return _resultValue;
        }
    }
}
