// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gcp.observability;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.gcp.Utilities;
import com.pulumi.gcp.observability.BucketArgs;
import com.pulumi.gcp.observability.inputs.BucketState;
import com.pulumi.gcp.observability.outputs.BucketCmekSettings;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Bucket configuration for storing observability data.
 * 
 * ## Example Usage
 * 
 * ## Import
 * 
 * Bucket can be imported using any of these accepted formats:
 * 
 * * `projects/{{project}}/locations/{{location}}/buckets/{{bucket_id}}`
 * * `{{project}}/{{location}}/{{bucket_id}}`
 * * `{{location}}/{{bucket_id}}`
 * 
 * When using the `pulumi import` command, Bucket can be imported using one of the formats above. For example:
 * 
 * ```sh
 * $ pulumi import gcp:observability/bucket:Bucket default projects/{{project}}/locations/{{location}}/buckets/{{bucket_id}}
 * $ pulumi import gcp:observability/bucket:Bucket default {{project}}/{{location}}/{{bucket_id}}
 * $ pulumi import gcp:observability/bucket:Bucket default {{location}}/{{bucket_id}}
 * ```
 * 
 */
@ResourceType(type="gcp:observability/bucket:Bucket")
public class Bucket extends com.pulumi.resources.CustomResource {
    /**
     * A client-assigned identifier for the bucket.
     * 
     */
    @Export(name="bucketId", refs={String.class}, tree="[0]")
    private Output<String> bucketId;

    /**
     * @return A client-assigned identifier for the bucket.
     * 
     */
    public Output<String> bucketId() {
        return this.bucketId;
    }
    /**
     * Settings for configuring CMEK for a bucket.
     * Structure is documented below.
     * 
     */
    @Export(name="cmekSettings", refs={BucketCmekSettings.class}, tree="[0]")
    private Output</* @Nullable */ BucketCmekSettings> cmekSettings;

    /**
     * @return Settings for configuring CMEK for a bucket.
     * Structure is documented below.
     * 
     */
    public Output<Optional<BucketCmekSettings>> cmekSettings() {
        return Codegen.optional(this.cmekSettings);
    }
    /**
     * Output only. Create timestamp.
     * 
     */
    @Export(name="createTime", refs={String.class}, tree="[0]")
    private Output<String> createTime;

    /**
     * @return Output only. Create timestamp.
     * 
     */
    public Output<String> createTime() {
        return this.createTime;
    }
    /**
     * Output only. Delete timestamp.
     * 
     */
    @Export(name="deleteTime", refs={String.class}, tree="[0]")
    private Output<String> deleteTime;

    /**
     * @return Output only. Delete timestamp.
     * 
     */
    public Output<String> deleteTime() {
        return this.deleteTime;
    }
    /**
     * Description of the bucket.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output<String> description;

    /**
     * @return Description of the bucket.
     * 
     */
    public Output<String> description() {
        return this.description;
    }
    /**
     * User friendly display name.
     * 
     */
    @Export(name="displayName", refs={String.class}, tree="[0]")
    private Output<String> displayName;

    /**
     * @return User friendly display name.
     * 
     */
    public Output<String> displayName() {
        return this.displayName;
    }
    /**
     * The location of the bucket.
     * 
     */
    @Export(name="location", refs={String.class}, tree="[0]")
    private Output<String> location;

    /**
     * @return The location of the bucket.
     * 
     */
    public Output<String> location() {
        return this.location;
    }
    /**
     * Identifier. Name of the bucket. The format is: projects/[PROJECT_ID]/locations/[LOCATION]/buckets/[BUCKET_ID]
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Identifier. Name of the bucket. The format is: projects/[PROJECT_ID]/locations/[LOCATION]/buckets/[BUCKET_ID]
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The ID of the project in which the resource belongs.
     * If it is not provided, the provider project is used.
     * 
     */
    @Export(name="project", refs={String.class}, tree="[0]")
    private Output<String> project;

    /**
     * @return The ID of the project in which the resource belongs.
     * If it is not provided, the provider project is used.
     * 
     */
    public Output<String> project() {
        return this.project;
    }
    /**
     * Output only. Timestamp when the bucket in soft-deleted state is purged.
     * 
     */
    @Export(name="purgeTime", refs={String.class}, tree="[0]")
    private Output<String> purgeTime;

    /**
     * @return Output only. Timestamp when the bucket in soft-deleted state is purged.
     * 
     */
    public Output<String> purgeTime() {
        return this.purgeTime;
    }
    /**
     * Output only. Update timestamp.
     * 
     */
    @Export(name="updateTime", refs={String.class}, tree="[0]")
    private Output<String> updateTime;

    /**
     * @return Output only. Update timestamp.
     * 
     */
    public Output<String> updateTime() {
        return this.updateTime;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Bucket(java.lang.String name) {
        this(name, BucketArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Bucket(java.lang.String name, BucketArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Bucket(java.lang.String name, BucketArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("gcp:observability/bucket:Bucket", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Bucket(java.lang.String name, Output<java.lang.String> id, @Nullable BucketState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("gcp:observability/bucket:Bucket", name, state, makeResourceOptions(options, id), false);
    }

    private static BucketArgs makeArgs(BucketArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? BucketArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Bucket get(java.lang.String name, Output<java.lang.String> id, @Nullable BucketState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Bucket(name, id, state, options);
    }
}
