// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gcp.networksecurity.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class SecurityProfileWildfireAnalysisProfileWildfireInlineMlSettingInlineMlConfig {
    /**
     * @return The action to take for a file type.
     * Possible values are: `DISABLE`, `ALERT`, `ENABLE`.
     * 
     */
    private String action;
    /**
     * @return The file type to match. For allowed values, see [API docs](https://docs.cloud.google.com/firewall/docs/reference/network-security/rest/v1beta1/organizations.locations.securityProfiles#inlinemlfiletype)
     * 
     */
    private String fileType;

    private SecurityProfileWildfireAnalysisProfileWildfireInlineMlSettingInlineMlConfig() {}
    /**
     * @return The action to take for a file type.
     * Possible values are: `DISABLE`, `ALERT`, `ENABLE`.
     * 
     */
    public String action() {
        return this.action;
    }
    /**
     * @return The file type to match. For allowed values, see [API docs](https://docs.cloud.google.com/firewall/docs/reference/network-security/rest/v1beta1/organizations.locations.securityProfiles#inlinemlfiletype)
     * 
     */
    public String fileType() {
        return this.fileType;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SecurityProfileWildfireAnalysisProfileWildfireInlineMlSettingInlineMlConfig defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String action;
        private String fileType;
        public Builder() {}
        public Builder(SecurityProfileWildfireAnalysisProfileWildfireInlineMlSettingInlineMlConfig defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.action = defaults.action;
    	      this.fileType = defaults.fileType;
        }

        @CustomType.Setter
        public Builder action(String action) {
            if (action == null) {
              throw new MissingRequiredPropertyException("SecurityProfileWildfireAnalysisProfileWildfireInlineMlSettingInlineMlConfig", "action");
            }
            this.action = action;
            return this;
        }
        @CustomType.Setter
        public Builder fileType(String fileType) {
            if (fileType == null) {
              throw new MissingRequiredPropertyException("SecurityProfileWildfireAnalysisProfileWildfireInlineMlSettingInlineMlConfig", "fileType");
            }
            this.fileType = fileType;
            return this;
        }
        public SecurityProfileWildfireAnalysisProfileWildfireInlineMlSettingInlineMlConfig build() {
            final var _resultValue = new SecurityProfileWildfireAnalysisProfileWildfireInlineMlSettingInlineMlConfig();
            _resultValue.action = action;
            _resultValue.fileType = fileType;
            return _resultValue;
        }
    }
}
