// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Gcp.MigrationCenter.Inputs
{

    public sealed class AssetsExportJobRecentExecutionResultArgs : global::Pulumi.ResourceArgs
    {
        [Input("errors")]
        private InputList<Inputs.AssetsExportJobRecentExecutionResultErrorArgs>? _errors;

        /// <summary>
        /// (Output)
        /// The `Status` type defines a logical error model that is suitable for
        /// different programming environments, including REST APIs and RPC APIs. It is
        /// used by [gRPC](https://github.com/grpc). Each `Status` message contains
        /// three pieces of data: error code, error message, and error details.
        /// You can find out more about this error model and how to work with it in the
        /// [API Design Guide](https://cloud.google.com/apis/design/errors).
        /// Structure is documented below.
        /// </summary>
        public InputList<Inputs.AssetsExportJobRecentExecutionResultErrorArgs> Errors
        {
            get => _errors ?? (_errors = new InputList<Inputs.AssetsExportJobRecentExecutionResultErrorArgs>());
            set => _errors = value;
        }

        [Input("outputFiles")]
        private InputList<Inputs.AssetsExportJobRecentExecutionResultOutputFileArgs>? _outputFiles;

        /// <summary>
        /// (Output)
        /// Contains a list of output files.
        /// Structure is documented below.
        /// </summary>
        public InputList<Inputs.AssetsExportJobRecentExecutionResultOutputFileArgs> OutputFiles
        {
            get => _outputFiles ?? (_outputFiles = new InputList<Inputs.AssetsExportJobRecentExecutionResultOutputFileArgs>());
            set => _outputFiles = value;
        }

        [Input("signedUris")]
        private InputList<Inputs.AssetsExportJobRecentExecutionResultSignedUriArgs>? _signedUris;

        /// <summary>
        /// (Output)
        /// List of signed URIs.
        /// Structure is documented below.
        /// </summary>
        public InputList<Inputs.AssetsExportJobRecentExecutionResultSignedUriArgs> SignedUris
        {
            get => _signedUris ?? (_signedUris = new InputList<Inputs.AssetsExportJobRecentExecutionResultSignedUriArgs>());
            set => _signedUris = value;
        }

        public AssetsExportJobRecentExecutionResultArgs()
        {
        }
        public static new AssetsExportJobRecentExecutionResultArgs Empty => new AssetsExportJobRecentExecutionResultArgs();
    }
}
