// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Gcp.MigrationCenter.Inputs
{

    public sealed class ReportSummaryGroupFindingPreferenceSetFindingArgs : global::Pulumi.ResourceArgs
    {
        [Input("computeEngineFindings")]
        private InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingComputeEngineFindingArgs>? _computeEngineFindings;

        /// <summary>
        /// (Output)
        /// A set of findings that applies to assets destined for Compute Engine.
        /// Structure is documented below.
        /// </summary>
        public InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingComputeEngineFindingArgs> ComputeEngineFindings
        {
            get => _computeEngineFindings ?? (_computeEngineFindings = new InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingComputeEngineFindingArgs>());
            set => _computeEngineFindings = value;
        }

        /// <summary>
        /// Free-text description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// User-friendly display name. Maximum length is 63 characters.
        /// </summary>
        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        [Input("machinePreferences")]
        private InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingMachinePreferenceArgs>? _machinePreferences;

        /// <summary>
        /// (Output)
        /// The type of machines to consider when calculating virtual machine migration
        /// insights and recommendations.
        /// Not all machine types are available in all zones and regions.
        /// Structure is documented below.
        /// </summary>
        public InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingMachinePreferenceArgs> MachinePreferences
        {
            get => _machinePreferences ?? (_machinePreferences = new InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingMachinePreferenceArgs>());
            set => _machinePreferences = value;
        }

        [Input("monthlyCostComputes")]
        private InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingMonthlyCostComputeArgs>? _monthlyCostComputes;

        /// <summary>
        /// (Output)
        /// Represents an amount of money with its currency type.
        /// Structure is documented below.
        /// </summary>
        public InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingMonthlyCostComputeArgs> MonthlyCostComputes
        {
            get => _monthlyCostComputes ?? (_monthlyCostComputes = new InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingMonthlyCostComputeArgs>());
            set => _monthlyCostComputes = value;
        }

        [Input("monthlyCostNetworkEgresses")]
        private InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingMonthlyCostNetworkEgressArgs>? _monthlyCostNetworkEgresses;

        /// <summary>
        /// (Output)
        /// Represents an amount of money with its currency type.
        /// Structure is documented below.
        /// </summary>
        public InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingMonthlyCostNetworkEgressArgs> MonthlyCostNetworkEgresses
        {
            get => _monthlyCostNetworkEgresses ?? (_monthlyCostNetworkEgresses = new InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingMonthlyCostNetworkEgressArgs>());
            set => _monthlyCostNetworkEgresses = value;
        }

        [Input("monthlyCostOsLicenses")]
        private InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingMonthlyCostOsLicenseArgs>? _monthlyCostOsLicenses;

        /// <summary>
        /// (Output)
        /// Represents an amount of money with its currency type.
        /// Structure is documented below.
        /// </summary>
        public InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingMonthlyCostOsLicenseArgs> MonthlyCostOsLicenses
        {
            get => _monthlyCostOsLicenses ?? (_monthlyCostOsLicenses = new InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingMonthlyCostOsLicenseArgs>());
            set => _monthlyCostOsLicenses = value;
        }

        [Input("monthlyCostOthers")]
        private InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingMonthlyCostOtherArgs>? _monthlyCostOthers;

        /// <summary>
        /// (Output)
        /// Represents an amount of money with its currency type.
        /// Structure is documented below.
        /// </summary>
        public InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingMonthlyCostOtherArgs> MonthlyCostOthers
        {
            get => _monthlyCostOthers ?? (_monthlyCostOthers = new InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingMonthlyCostOtherArgs>());
            set => _monthlyCostOthers = value;
        }

        [Input("monthlyCostStorages")]
        private InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingMonthlyCostStorageArgs>? _monthlyCostStorages;

        /// <summary>
        /// (Output)
        /// Represents an amount of money with its currency type.
        /// Structure is documented below.
        /// </summary>
        public InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingMonthlyCostStorageArgs> MonthlyCostStorages
        {
            get => _monthlyCostStorages ?? (_monthlyCostStorages = new InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingMonthlyCostStorageArgs>());
            set => _monthlyCostStorages = value;
        }

        [Input("monthlyCostTotals")]
        private InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingMonthlyCostTotalArgs>? _monthlyCostTotals;

        /// <summary>
        /// (Output)
        /// Represents an amount of money with its currency type.
        /// Structure is documented below.
        /// </summary>
        public InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingMonthlyCostTotalArgs> MonthlyCostTotals
        {
            get => _monthlyCostTotals ?? (_monthlyCostTotals = new InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingMonthlyCostTotalArgs>());
            set => _monthlyCostTotals = value;
        }

        [Input("soleTenantFindings")]
        private InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingSoleTenantFindingArgs>? _soleTenantFindings;

        /// <summary>
        /// (Output)
        /// A set of findings that applies to assets destined for Sole-Tenant nodes.
        /// Structure is documented below.
        /// </summary>
        public InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingSoleTenantFindingArgs> SoleTenantFindings
        {
            get => _soleTenantFindings ?? (_soleTenantFindings = new InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingSoleTenantFindingArgs>());
            set => _soleTenantFindings = value;
        }

        [Input("vmwareEngineFindings")]
        private InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingVmwareEngineFindingArgs>? _vmwareEngineFindings;

        /// <summary>
        /// (Output)
        /// A set of findings that applies to assets destined for VMWare Engine.
        /// Structure is documented below.
        /// </summary>
        public InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingVmwareEngineFindingArgs> VmwareEngineFindings
        {
            get => _vmwareEngineFindings ?? (_vmwareEngineFindings = new InputList<Inputs.ReportSummaryGroupFindingPreferenceSetFindingVmwareEngineFindingArgs>());
            set => _vmwareEngineFindings = value;
        }

        public ReportSummaryGroupFindingPreferenceSetFindingArgs()
        {
        }
        public static new ReportSummaryGroupFindingPreferenceSetFindingArgs Empty => new ReportSummaryGroupFindingPreferenceSetFindingArgs();
    }
}
