// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Gcp.OracleDatabase.Inputs
{

    public sealed class AutonomousDatabasePropertiesCustomerContactGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The email address used by Oracle to send notifications regarding databases
        /// and infrastructure.
        /// 
        /// &lt;a name="NestedPropertiesApexDetails"&gt;&lt;/a&gt;The `ApexDetails` block contains:
        /// </summary>
        [Input("email", required: true)]
        public Input<string> Email { get; set; } = null!;

        public AutonomousDatabasePropertiesCustomerContactGetArgs()
        {
        }
        public static new AutonomousDatabasePropertiesCustomerContactGetArgs Empty => new AutonomousDatabasePropertiesCustomerContactGetArgs();
    }
}
