// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Gcp.OracleDatabase.Outputs
{

    [OutputType]
    public sealed class GoldengateConnectionPropertiesMysqlConnectionProperties
    {
        /// <summary>
        /// An array of name-value pair attribute entries.
        /// Used as additional parameters in connection string.
        /// Structure is documented below.
        /// </summary>
        public readonly ImmutableArray<Outputs.GoldengateConnectionPropertiesMysqlConnectionPropertiesAdditionalAttribute> AdditionalAttributes;
        /// <summary>
        /// The name of the database.
        /// </summary>
        public readonly string? Database;
        /// <summary>
        /// The OCID of the database system being referenced.
        /// </summary>
        public readonly string? DbSystemId;
        /// <summary>
        /// The name or address of a host.
        /// </summary>
        public readonly string? Host;
        /// <summary>
        /// Input only. The password Oracle Goldengate uses to connect to MySQL in plain text.
        /// </summary>
        public readonly string? Password;
        /// <summary>
        /// Input only. The resource name of a secret version in Secret Manager which contains
        /// the password Oracle Goldengate uses to connect to MySQL.
        /// Format: projects/{project}/secrets/{secret}/versions/{version}.
        /// </summary>
        public readonly string? PasswordSecretVersion;
        /// <summary>
        /// The port of an endpoint usually specified for a connection.
        /// </summary>
        public readonly int? Port;
        /// <summary>
        /// Security Type for MySQL.
        /// Possible values:
        /// PLAIN
        /// TLS
        /// MTLS
        /// </summary>
        public readonly string? SecurityProtocol;
        /// <summary>
        /// Database Certificate - The content of a .pem or .crt file
        /// containing the server public key (for 1 and 2-way SSL).
        /// </summary>
        public readonly string? SslCaFile;
        /// <summary>
        /// Client Certificate - The content of a .pem or .crt file
        /// containing the client public key (for 2-way SSL).
        /// </summary>
        public readonly string? SslCertFile;
        /// <summary>
        /// The list of certificates revoked by the trusted
        /// certificate authorities (Trusted CA).
        /// </summary>
        public readonly string? SslCrlFile;
        /// <summary>
        /// Client Key - The content of a .pem or .crt file containing
        /// the client private key (for 2-way SSL).
        /// </summary>
        public readonly string? SslKeyFile;
        /// <summary>
        /// SSL modes for MySQL.
        /// Possible values:
        /// DISABLED
        /// PREFERRED
        /// REQUIRED
        /// VERIFY_CA
        /// VERIFY_IDENTITY
        /// </summary>
        public readonly string? SslMode;
        /// <summary>
        /// The technology type of MysqlConnection.
        /// </summary>
        public readonly string? TechnologyType;
        /// <summary>
        /// The username Oracle Goldengate uses to connect the associated system of
        /// the given technology.
        /// </summary>
        public readonly string? Username;

        [OutputConstructor]
        private GoldengateConnectionPropertiesMysqlConnectionProperties(
            ImmutableArray<Outputs.GoldengateConnectionPropertiesMysqlConnectionPropertiesAdditionalAttribute> additionalAttributes,

            string? database,

            string? dbSystemId,

            string? host,

            string? password,

            string? passwordSecretVersion,

            int? port,

            string? securityProtocol,

            string? sslCaFile,

            string? sslCertFile,

            string? sslCrlFile,

            string? sslKeyFile,

            string? sslMode,

            string? technologyType,

            string? username)
        {
            AdditionalAttributes = additionalAttributes;
            Database = database;
            DbSystemId = dbSystemId;
            Host = host;
            Password = password;
            PasswordSecretVersion = passwordSecretVersion;
            Port = port;
            SecurityProtocol = securityProtocol;
            SslCaFile = sslCaFile;
            SslCertFile = sslCertFile;
            SslCrlFile = sslCrlFile;
            SslKeyFile = sslKeyFile;
            SslMode = sslMode;
            TechnologyType = technologyType;
            Username = username;
        }
    }
}
