// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gcp.cloudsecuritycompliance.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.gcp.cloudsecuritycompliance.outputs.CloudControlParameterSpecDefaultValueOneofValueParameterValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class CloudControlParameterSpecDefaultValueOneofValue {
    /**
     * @return The name of the parameter.
     * 
     */
    private @Nullable String name;
    /**
     * @return The value of the parameter.
     * Structure is documented below.
     * 
     */
    private @Nullable CloudControlParameterSpecDefaultValueOneofValueParameterValue parameterValue;

    private CloudControlParameterSpecDefaultValueOneofValue() {}
    /**
     * @return The name of the parameter.
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    /**
     * @return The value of the parameter.
     * Structure is documented below.
     * 
     */
    public Optional<CloudControlParameterSpecDefaultValueOneofValueParameterValue> parameterValue() {
        return Optional.ofNullable(this.parameterValue);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(CloudControlParameterSpecDefaultValueOneofValue defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String name;
        private @Nullable CloudControlParameterSpecDefaultValueOneofValueParameterValue parameterValue;
        public Builder() {}
        public Builder(CloudControlParameterSpecDefaultValueOneofValue defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.name = defaults.name;
    	      this.parameterValue = defaults.parameterValue;
        }

        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder parameterValue(@Nullable CloudControlParameterSpecDefaultValueOneofValueParameterValue parameterValue) {

            this.parameterValue = parameterValue;
            return this;
        }
        public CloudControlParameterSpecDefaultValueOneofValue build() {
            final var _resultValue = new CloudControlParameterSpecDefaultValueOneofValue();
            _resultValue.name = name;
            _resultValue.parameterValue = parameterValue;
            return _resultValue;
        }
    }
}
