// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Gcp.Compute.Outputs
{

    [OutputType]
    public sealed class InstanceFromTemplateNetworkInterface
    {
        public readonly ImmutableArray<Outputs.InstanceFromTemplateNetworkInterfaceAccessConfig> AccessConfigs;
        public readonly ImmutableArray<Outputs.InstanceFromTemplateNetworkInterfaceAliasIpRange> AliasIpRanges;
        /// <summary>
        /// A unique name for the resource, required by GCE.
        /// Changing this forces a new resource to be created.
        /// </summary>
        public readonly string? Name;
        public readonly string? Network;
        public readonly string? NetworkIp;
        public readonly string? NicType;
        public readonly string? Subnetwork;
        public readonly string? SubnetworkProject;

        [OutputConstructor]
        private InstanceFromTemplateNetworkInterface(
            ImmutableArray<Outputs.InstanceFromTemplateNetworkInterfaceAccessConfig> accessConfigs,

            ImmutableArray<Outputs.InstanceFromTemplateNetworkInterfaceAliasIpRange> aliasIpRanges,

            string? name,

            string? network,

            string? networkIp,

            string? nicType,

            string? subnetwork,

            string? subnetworkProject)
        {
            AccessConfigs = accessConfigs;
            AliasIpRanges = aliasIpRanges;
            Name = name;
            Network = network;
            NetworkIp = networkIp;
            NicType = nicType;
            Subnetwork = subnetwork;
            SubnetworkProject = subnetworkProject;
        }
    }
}
