# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'InstanceAccessRulesOptions',
    'InstanceAccessRulesOptionsAccessRule',
    'GetInstanceAccessRulesOptionResult',
    'GetInstanceAccessRulesOptionAccessRuleResult',
]

@pulumi.output_type
class InstanceAccessRulesOptions(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "defaultSquashMode":
            suggest = "default_squash_mode"
        elif key == "accessRules":
            suggest = "access_rules"
        elif key == "defaultSquashGid":
            suggest = "default_squash_gid"
        elif key == "defaultSquashUid":
            suggest = "default_squash_uid"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in InstanceAccessRulesOptions. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        InstanceAccessRulesOptions.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        InstanceAccessRulesOptions.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 default_squash_mode: _builtins.str,
                 access_rules: Optional[Sequence['outputs.InstanceAccessRulesOptionsAccessRule']] = None,
                 default_squash_gid: Optional[_builtins.int] = None,
                 default_squash_uid: Optional[_builtins.int] = None):
        """
        :param _builtins.str default_squash_mode: Set to "ROOT_SQUASH" to enable root squashing by default.
               Other values include "NO_SQUASH".
               Possible values are: `ROOT_SQUASH`, `NO_SQUASH`.
        :param Sequence['InstanceAccessRulesOptionsAccessRuleArgs'] access_rules: An array of access rule exceptions. Each rule defines IP address ranges
               that should have different squash behavior than the default.
               Structure is documented below.
        :param _builtins.int default_squash_gid: The GID to map the root user to when root squashing is enabled
               (e.g., 65534 for nobody).
        :param _builtins.int default_squash_uid: The UID to map the root user to when root squashing is enabled
               (e.g., 65534 for nobody).
        """
        pulumi.set(__self__, "default_squash_mode", default_squash_mode)
        if access_rules is not None:
            pulumi.set(__self__, "access_rules", access_rules)
        if default_squash_gid is not None:
            pulumi.set(__self__, "default_squash_gid", default_squash_gid)
        if default_squash_uid is not None:
            pulumi.set(__self__, "default_squash_uid", default_squash_uid)

    @_builtins.property
    @pulumi.getter(name="defaultSquashMode")
    def default_squash_mode(self) -> _builtins.str:
        """
        Set to "ROOT_SQUASH" to enable root squashing by default.
        Other values include "NO_SQUASH".
        Possible values are: `ROOT_SQUASH`, `NO_SQUASH`.
        """
        return pulumi.get(self, "default_squash_mode")

    @_builtins.property
    @pulumi.getter(name="accessRules")
    def access_rules(self) -> Optional[Sequence['outputs.InstanceAccessRulesOptionsAccessRule']]:
        """
        An array of access rule exceptions. Each rule defines IP address ranges
        that should have different squash behavior than the default.
        Structure is documented below.
        """
        return pulumi.get(self, "access_rules")

    @_builtins.property
    @pulumi.getter(name="defaultSquashGid")
    def default_squash_gid(self) -> Optional[_builtins.int]:
        """
        The GID to map the root user to when root squashing is enabled
        (e.g., 65534 for nobody).
        """
        return pulumi.get(self, "default_squash_gid")

    @_builtins.property
    @pulumi.getter(name="defaultSquashUid")
    def default_squash_uid(self) -> Optional[_builtins.int]:
        """
        The UID to map the root user to when root squashing is enabled
        (e.g., 65534 for nobody).
        """
        return pulumi.get(self, "default_squash_uid")


@pulumi.output_type
class InstanceAccessRulesOptionsAccessRule(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "ipAddressRanges":
            suggest = "ip_address_ranges"
        elif key == "squashMode":
            suggest = "squash_mode"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in InstanceAccessRulesOptionsAccessRule. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        InstanceAccessRulesOptionsAccessRule.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        InstanceAccessRulesOptionsAccessRule.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 ip_address_ranges: Sequence[_builtins.str],
                 name: _builtins.str,
                 squash_mode: _builtins.str):
        """
        :param Sequence[_builtins.str] ip_address_ranges: An array of IP address strings or CIDR ranges that this rule applies to.
        :param _builtins.str name: A unique identifier for the access rule.
        :param _builtins.str squash_mode: The squash mode for this specific rule. Currently, only "NO_SQUASH"
               is supported for exceptions.
               Possible values are: `NO_SQUASH`.
        """
        pulumi.set(__self__, "ip_address_ranges", ip_address_ranges)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "squash_mode", squash_mode)

    @_builtins.property
    @pulumi.getter(name="ipAddressRanges")
    def ip_address_ranges(self) -> Sequence[_builtins.str]:
        """
        An array of IP address strings or CIDR ranges that this rule applies to.
        """
        return pulumi.get(self, "ip_address_ranges")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        A unique identifier for the access rule.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="squashMode")
    def squash_mode(self) -> _builtins.str:
        """
        The squash mode for this specific rule. Currently, only "NO_SQUASH"
        is supported for exceptions.
        Possible values are: `NO_SQUASH`.
        """
        return pulumi.get(self, "squash_mode")


@pulumi.output_type
class GetInstanceAccessRulesOptionResult(dict):
    def __init__(__self__, *,
                 access_rules: Sequence['outputs.GetInstanceAccessRulesOptionAccessRuleResult'],
                 default_squash_gid: _builtins.int,
                 default_squash_mode: _builtins.str,
                 default_squash_uid: _builtins.int):
        """
        :param Sequence['GetInstanceAccessRulesOptionAccessRuleArgs'] access_rules: An array of access rule exceptions. Each rule defines IP address ranges
               that should have different squash behavior than the default.
        :param _builtins.int default_squash_gid: The GID to map the root user to when root squashing is enabled
               (e.g., 65534 for nobody).
        :param _builtins.str default_squash_mode: Set to "ROOT_SQUASH" to enable root squashing by default.
               Other values include "NO_SQUASH". Possible values: ["ROOT_SQUASH", "NO_SQUASH"]
        :param _builtins.int default_squash_uid: The UID to map the root user to when root squashing is enabled
               (e.g., 65534 for nobody).
        """
        pulumi.set(__self__, "access_rules", access_rules)
        pulumi.set(__self__, "default_squash_gid", default_squash_gid)
        pulumi.set(__self__, "default_squash_mode", default_squash_mode)
        pulumi.set(__self__, "default_squash_uid", default_squash_uid)

    @_builtins.property
    @pulumi.getter(name="accessRules")
    def access_rules(self) -> Sequence['outputs.GetInstanceAccessRulesOptionAccessRuleResult']:
        """
        An array of access rule exceptions. Each rule defines IP address ranges
        that should have different squash behavior than the default.
        """
        return pulumi.get(self, "access_rules")

    @_builtins.property
    @pulumi.getter(name="defaultSquashGid")
    def default_squash_gid(self) -> _builtins.int:
        """
        The GID to map the root user to when root squashing is enabled
        (e.g., 65534 for nobody).
        """
        return pulumi.get(self, "default_squash_gid")

    @_builtins.property
    @pulumi.getter(name="defaultSquashMode")
    def default_squash_mode(self) -> _builtins.str:
        """
        Set to "ROOT_SQUASH" to enable root squashing by default.
        Other values include "NO_SQUASH". Possible values: ["ROOT_SQUASH", "NO_SQUASH"]
        """
        return pulumi.get(self, "default_squash_mode")

    @_builtins.property
    @pulumi.getter(name="defaultSquashUid")
    def default_squash_uid(self) -> _builtins.int:
        """
        The UID to map the root user to when root squashing is enabled
        (e.g., 65534 for nobody).
        """
        return pulumi.get(self, "default_squash_uid")


@pulumi.output_type
class GetInstanceAccessRulesOptionAccessRuleResult(dict):
    def __init__(__self__, *,
                 ip_address_ranges: Sequence[_builtins.str],
                 name: _builtins.str,
                 squash_mode: _builtins.str):
        """
        :param Sequence[_builtins.str] ip_address_ranges: An array of IP address strings or CIDR ranges that this rule applies to.
        :param _builtins.str name: A unique identifier for the access rule.
        :param _builtins.str squash_mode: The squash mode for this specific rule. Currently, only "NO_SQUASH"
               is supported for exceptions. Possible values: ["NO_SQUASH"]
        """
        pulumi.set(__self__, "ip_address_ranges", ip_address_ranges)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "squash_mode", squash_mode)

    @_builtins.property
    @pulumi.getter(name="ipAddressRanges")
    def ip_address_ranges(self) -> Sequence[_builtins.str]:
        """
        An array of IP address strings or CIDR ranges that this rule applies to.
        """
        return pulumi.get(self, "ip_address_ranges")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        A unique identifier for the access rule.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="squashMode")
    def squash_mode(self) -> _builtins.str:
        """
        The squash mode for this specific rule. Currently, only "NO_SQUASH"
        is supported for exceptions. Possible values: ["NO_SQUASH"]
        """
        return pulumi.get(self, "squash_mode")


