// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gcp.diagflow.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class CxToolOpenApiSpecAuthenticationServiceAgentAuthConfig {
    /**
     * @return Optional. Indicate the auth token type generated from the Diglogflow service agent.
     * The generated token is sent in the Authorization header.
     * See [ServiceAgentAuth](https://cloud.google.com/dialogflow/cx/docs/reference/rest/v3/projects.locations.agents.tools#serviceagentauth) for valid values.
     * 
     */
    private @Nullable String serviceAgentAuth;

    private CxToolOpenApiSpecAuthenticationServiceAgentAuthConfig() {}
    /**
     * @return Optional. Indicate the auth token type generated from the Diglogflow service agent.
     * The generated token is sent in the Authorization header.
     * See [ServiceAgentAuth](https://cloud.google.com/dialogflow/cx/docs/reference/rest/v3/projects.locations.agents.tools#serviceagentauth) for valid values.
     * 
     */
    public Optional<String> serviceAgentAuth() {
        return Optional.ofNullable(this.serviceAgentAuth);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(CxToolOpenApiSpecAuthenticationServiceAgentAuthConfig defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String serviceAgentAuth;
        public Builder() {}
        public Builder(CxToolOpenApiSpecAuthenticationServiceAgentAuthConfig defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.serviceAgentAuth = defaults.serviceAgentAuth;
        }

        @CustomType.Setter
        public Builder serviceAgentAuth(@Nullable String serviceAgentAuth) {

            this.serviceAgentAuth = serviceAgentAuth;
            return this;
        }
        public CxToolOpenApiSpecAuthenticationServiceAgentAuthConfig build() {
            final var _resultValue = new CxToolOpenApiSpecAuthenticationServiceAgentAuthConfig();
            _resultValue.serviceAgentAuth = serviceAgentAuth;
            return _resultValue;
        }
    }
}
