// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gcp.transcoder.inputs;




public final class JobTemplateConfigEncryptionAes128Args extends com.pulumi.resources.ResourceArgs {

    public static final JobTemplateConfigEncryptionAes128Args Empty = new JobTemplateConfigEncryptionAes128Args();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private JobTemplateConfigEncryptionAes128Args $;

        public Builder() {
            $ = new JobTemplateConfigEncryptionAes128Args();
        }
        public JobTemplateConfigEncryptionAes128Args build() {
            return $;
        }
    }

}
