// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gcp.identityplatform.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class TenantClientPermissionsArgs extends com.pulumi.resources.ResourceArgs {

    public static final TenantClientPermissionsArgs Empty = new TenantClientPermissionsArgs();

    /**
     * When true, end users cannot delete their account on the associated project through any of our API methods.
     * 
     */
    @Import(name="disabledUserDeletion")
    private @Nullable Output<Boolean> disabledUserDeletion;

    /**
     * @return When true, end users cannot delete their account on the associated project through any of our API methods.
     * 
     */
    public Optional<Output<Boolean>> disabledUserDeletion() {
        return Optional.ofNullable(this.disabledUserDeletion);
    }

    /**
     * When true, end users cannot sign up for a new account on the associated project through any of our API methods.
     * 
     */
    @Import(name="disabledUserSignup")
    private @Nullable Output<Boolean> disabledUserSignup;

    /**
     * @return When true, end users cannot sign up for a new account on the associated project through any of our API methods.
     * 
     */
    public Optional<Output<Boolean>> disabledUserSignup() {
        return Optional.ofNullable(this.disabledUserSignup);
    }

    private TenantClientPermissionsArgs() {}

    private TenantClientPermissionsArgs(TenantClientPermissionsArgs $) {
        this.disabledUserDeletion = $.disabledUserDeletion;
        this.disabledUserSignup = $.disabledUserSignup;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TenantClientPermissionsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TenantClientPermissionsArgs $;

        public Builder() {
            $ = new TenantClientPermissionsArgs();
        }

        public Builder(TenantClientPermissionsArgs defaults) {
            $ = new TenantClientPermissionsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param disabledUserDeletion When true, end users cannot delete their account on the associated project through any of our API methods.
         * 
         * @return builder
         * 
         */
        public Builder disabledUserDeletion(@Nullable Output<Boolean> disabledUserDeletion) {
            $.disabledUserDeletion = disabledUserDeletion;
            return this;
        }

        /**
         * @param disabledUserDeletion When true, end users cannot delete their account on the associated project through any of our API methods.
         * 
         * @return builder
         * 
         */
        public Builder disabledUserDeletion(Boolean disabledUserDeletion) {
            return disabledUserDeletion(Output.of(disabledUserDeletion));
        }

        /**
         * @param disabledUserSignup When true, end users cannot sign up for a new account on the associated project through any of our API methods.
         * 
         * @return builder
         * 
         */
        public Builder disabledUserSignup(@Nullable Output<Boolean> disabledUserSignup) {
            $.disabledUserSignup = disabledUserSignup;
            return this;
        }

        /**
         * @param disabledUserSignup When true, end users cannot sign up for a new account on the associated project through any of our API methods.
         * 
         * @return builder
         * 
         */
        public Builder disabledUserSignup(Boolean disabledUserSignup) {
            return disabledUserSignup(Output.of(disabledUserSignup));
        }

        public TenantClientPermissionsArgs build() {
            return $;
        }
    }

}
