// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gcp.osconfig.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class PatchDeploymentPatchConfigYum {
    /**
     * @return List of packages to exclude from update. These packages will be excluded.
     * 
     */
    private @Nullable List<String> excludes;
    /**
     * @return An exclusive list of packages to be updated. These are the only packages that will be updated.
     * If these packages are not installed, they will be ignored. This field cannot be specified with
     * any other patch configuration fields.
     * 
     */
    private @Nullable List<String> exclusivePackages;
    /**
     * @return Will cause patch to run yum update-minimal instead.
     * 
     */
    private @Nullable Boolean minimal;
    /**
     * @return Adds the --security flag to yum update. Not supported on all platforms.
     * 
     */
    private @Nullable Boolean security;

    private PatchDeploymentPatchConfigYum() {}
    /**
     * @return List of packages to exclude from update. These packages will be excluded.
     * 
     */
    public List<String> excludes() {
        return this.excludes == null ? List.of() : this.excludes;
    }
    /**
     * @return An exclusive list of packages to be updated. These are the only packages that will be updated.
     * If these packages are not installed, they will be ignored. This field cannot be specified with
     * any other patch configuration fields.
     * 
     */
    public List<String> exclusivePackages() {
        return this.exclusivePackages == null ? List.of() : this.exclusivePackages;
    }
    /**
     * @return Will cause patch to run yum update-minimal instead.
     * 
     */
    public Optional<Boolean> minimal() {
        return Optional.ofNullable(this.minimal);
    }
    /**
     * @return Adds the --security flag to yum update. Not supported on all platforms.
     * 
     */
    public Optional<Boolean> security() {
        return Optional.ofNullable(this.security);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PatchDeploymentPatchConfigYum defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<String> excludes;
        private @Nullable List<String> exclusivePackages;
        private @Nullable Boolean minimal;
        private @Nullable Boolean security;
        public Builder() {}
        public Builder(PatchDeploymentPatchConfigYum defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.excludes = defaults.excludes;
    	      this.exclusivePackages = defaults.exclusivePackages;
    	      this.minimal = defaults.minimal;
    	      this.security = defaults.security;
        }

        @CustomType.Setter
        public Builder excludes(@Nullable List<String> excludes) {

            this.excludes = excludes;
            return this;
        }
        public Builder excludes(String... excludes) {
            return excludes(List.of(excludes));
        }
        @CustomType.Setter
        public Builder exclusivePackages(@Nullable List<String> exclusivePackages) {

            this.exclusivePackages = exclusivePackages;
            return this;
        }
        public Builder exclusivePackages(String... exclusivePackages) {
            return exclusivePackages(List.of(exclusivePackages));
        }
        @CustomType.Setter
        public Builder minimal(@Nullable Boolean minimal) {

            this.minimal = minimal;
            return this;
        }
        @CustomType.Setter
        public Builder security(@Nullable Boolean security) {

            this.security = security;
            return this;
        }
        public PatchDeploymentPatchConfigYum build() {
            final var _resultValue = new PatchDeploymentPatchConfigYum();
            _resultValue.excludes = excludes;
            _resultValue.exclusivePackages = exclusivePackages;
            _resultValue.minimal = minimal;
            _resultValue.security = security;
            return _resultValue;
        }
    }
}
